name: rsprocess

channels:
    - astropy
    - defaults
    - conda-forge

dependencies:
    - python=3
    - astropy
    - Cython
    - matplotlib
    - numpy
    - sphinx-astropy
    - radio-beam
    - regions
